# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Omega/Image_processing/Image_processing.srcs/sources_1/bd/box/ip/box_axi_dma_0_0/box_axi_dma_0_0.xci
# IP: The module: 'box_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Omega/Image_processing/Image_processing.gen/sources_1/bd/box/ip/box_axi_dma_0_0/box_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'box_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Omega/Image_processing/Image_processing.gen/sources_1/bd/box/ip/box_axi_dma_0_0/box_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'box_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Omega/Image_processing/Image_processing.gen/sources_1/bd/box/ip/box_axi_dma_0_0/box_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'box_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Omega/Image_processing/Image_processing.srcs/sources_1/bd/box/ip/box_axi_dma_0_0/box_axi_dma_0_0.xci
# IP: The module: 'box_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Omega/Image_processing/Image_processing.gen/sources_1/bd/box/ip/box_axi_dma_0_0/box_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'box_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Omega/Image_processing/Image_processing.gen/sources_1/bd/box/ip/box_axi_dma_0_0/box_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'box_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Omega/Image_processing/Image_processing.gen/sources_1/bd/box/ip/box_axi_dma_0_0/box_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'box_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
