# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/box/box.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box || ORIG_REF_NAME==box} -quiet] -quiet

# IP: bd/box/ip/box_processing_system7_0_0/box_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_processing_system7_0_0 || ORIG_REF_NAME==box_processing_system7_0_0} -quiet] -quiet

# IP: bd/box/ip/box_axi_dma_0_0/box_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_axi_dma_0_0 || ORIG_REF_NAME==box_axi_dma_0_0} -quiet] -quiet

# IP: bd/box/ip/box_ps7_0_axi_periph_0/box_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_ps7_0_axi_periph_0 || ORIG_REF_NAME==box_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/box/ip/box_rst_ps7_0_100M_0/box_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_rst_ps7_0_100M_0 || ORIG_REF_NAME==box_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/box/ip/box_axis_dwidth_converter_0_0/box_axis_dwidth_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_axis_dwidth_converter_0_0 || ORIG_REF_NAME==box_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: bd/box/ip/box_xbar_0/box_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_xbar_0 || ORIG_REF_NAME==box_xbar_0} -quiet] -quiet

# IP: bd/box/ip/box_axi_mem_intercon_0/box_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_axi_mem_intercon_0 || ORIG_REF_NAME==box_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/box/ip/box_xlconcat_0_0/box_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_xlconcat_0_0 || ORIG_REF_NAME==box_xlconcat_0_0} -quiet] -quiet

# IP: bd/box/ip/box_boxBlur_0_0/box_boxBlur_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_boxBlur_0_0 || ORIG_REF_NAME==box_boxBlur_0_0} -quiet] -quiet

# IP: bd/box/ip/box_auto_pc_0/box_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_auto_pc_0 || ORIG_REF_NAME==box_auto_pc_0} -quiet] -quiet

# IP: bd/box/ip/box_auto_us_0/box_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_auto_us_0 || ORIG_REF_NAME==box_auto_us_0} -quiet] -quiet

# IP: bd/box/ip/box_auto_us_1/box_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_auto_us_1 || ORIG_REF_NAME==box_auto_us_1} -quiet] -quiet

# IP: bd/box/ip/box_auto_us_2/box_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_auto_us_2 || ORIG_REF_NAME==box_auto_us_2} -quiet] -quiet

# IP: bd/box/ip/box_auto_pc_1/box_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==box_auto_pc_1 || ORIG_REF_NAME==box_auto_pc_1} -quiet] -quiet

# XDC: c:/Omega/Image_processing/Image_processing.gen/sources_1/bd/box/box_ooc.xdc
