# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Omega/Image_processing/Image_processing.srcs/sources_1/bd/box/ip/box_boxBlur_0_0/box_boxBlur_0_0.xci
# IP: The module: 'box_boxBlur_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Omega/Image_processing/Image_processing.gen/sources_1/bd/box/ip/box_boxBlur_0_0/IP_S.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: c:/Omega/Image_processing/Image_processing.gen/sources_1/bd/box/ip/box_boxBlur_0_0/IP_S.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Omega/Image_processing/Image_processing.srcs/sources_1/bd/box/ip/box_boxBlur_0_0/box_boxBlur_0_0.xci
# IP: The module: 'box_boxBlur_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Omega/Image_processing/Image_processing.gen/sources_1/bd/box/ip/box_boxBlur_0_0/IP_S.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: c:/Omega/Image_processing/Image_processing.gen/sources_1/bd/box/ip/box_boxBlur_0_0/IP_S.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
